services:
  - type: web
    name: telegram-video-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: TOKEN
        sync: false
